cmake/custom/FindEigen3.cmake
@stigrj @ilfreddy With this change I was able to configure under EasyBuild:
```
ml notur
source mod_setup.sh
module load CMake
module load Eigen
export EIGEN3_ROOT=/global/hds/software/cpu/eb2/Eigen/3.2.9-foss-2016b
module load Boost
./setup --cc=icc --cxx=icpc
```
=> allow detecting eigen on easybuild; fixes #17

external/CMakeLists.txt, src/mrcpp/parallel.cpp
@bast: was there a reason why the compiler options were not passed on to xcfun (as they are to getkw)? This is probably not a problem unless xcfun is compiled "manually", see below.
The mrchem.h introduced a spurious dependency on getkw for mrcpp that was not passed to cmake, which broke the compilation (unless the external modes were compiled manually first). Now mrcpp is properly independent of the external modules and the order of compilation is
1) mrcpp
2) external modules (getkw and xcfun)
3) mrchem
=> Cmake issue

docs/installation.rst
Had to downgrade the intel compiler as something fails in OMP using intel/2016b. Also, changed to an older Eigen version since this one actually sets the EIGEN3_ROOT variable when the module is loaded (Eigen is header only, so compiler toolchain shouldn't matter).
=> update installation instructions

src/mrcpp/parallel.cpp
Related to the nasty memory bug in commit 5547a0530e4, where I removed sNodesCoeff from the SerialTree class and replaced it with a local variable in the routine it was used. This was not the actual bug, but I removed it from the class because it was never used outside the routine where it was assigned, and I **think** it still applies to the current changes. With this the code compiles and runs in MPI/OMP using intel/2015b, but there are still some bugs when running in MPI (see issues).
=> fix MPI compilation error

pilot/mrchem.cpp.sample, src/mrchem/MREnv.cpp, src/mrcpp/mwcore/ObjectCache.h, src/mrcpp/mwtrees/FunctionTree.h, src/mrcpp/mwtrees/MWNode.cpp, src/mrcpp/mwtrees/MWNode.h, src/mrcpp/mwtrees/MWTree.cpp, src/mrcpp/mwtrees/MWTree.h, src/mrcpp/mwtrees/SerialFunctionTree.cpp, src/mrcpp/mwtrees/SerialOperatorTree.cpp, src/mrcpp/parallel.h
The code did not compile without OMP due to improper "unparallelization" of Eigen. Also replaced the redundant #define OPENMP with HAVE_OPENMP
=> Compile issues

src/mrchem/MREnv.cpp, src/mrchem/qmfunctions/Density.cpp, src/mrchem/qmfunctions/Density.h, src/mrchem/qmfunctions/DensityProjector.cpp, src/mrchem/qmfunctions/Orbital.cpp, src/mrchem/qmfunctions/Orbital.h, src/mrchem/qmfunctions/OrbitalAdder.cpp, src/mrchem/qmfunctions/OrbitalProjector.cpp, src/mrchem/qmfunctions/OrbitalVector.cpp, src/mrchem/qmfunctions/OrbitalVector.h, src/mrchem/qmoperators/CoulombOperator.h, src/mrchem/qmoperators/ExchangePotential.cpp, src/mrchem/qmoperators/ExchangePotential.h, src/mrchem/qmoperators/FockOperator.cpp, src/mrchem/qmoperators/QMOperator.cpp, src/mrchem/scf_solver/EnergyOptimizer.cpp, src/mrchem/scf_solver/GroundStateSolver.cpp, src/mrchem/scf_solver/KAIN.cpp, src/mrchem/scf_solver/OrbitalOptimizer.cpp, src/mrchem/scf_solver/SCF.cpp, src/mrcpp/TelePrompter.cpp, src/mrcpp/mwtrees/FunctionTree.cpp, src/mrcpp/mwtrees/FunctionTree.h, src/mrcpp/mwtrees/MWNode.h, src/mrcpp/mwtrees/SerialFunctionTree.cpp, src/mrcpp/mwtrees/SerialOperatorTree.cpp, src/mrcpp/mwtrees/SerialTree.h, src/mrcpp/parallel.cpp, src/mrcpp/parallel.h
There are several issues we should discuss. Before accepting the pull request, you should at least check these points, as they concern the non-MPI section too:
1) I changed the "screening" precision in internal Exchange: it was  prec = getScaledPrecision(i, j) modified to  prec = std::max(getScaledPrecision(i, j), getScaledPrecision(j, i)).
The former did use the "i" precision also for the "j" orbital. Meaning that a different result can be obtained if the order of the orbitals is modified.
There are other ways of defining this too.
2)  In the testPreComputed I modified   (ex_i != 0) to (ex_i->getNNodes() != 0) as the former is never true (ex_i is defined, even if empty) . This condition was not used anyway I think.
3) I didn't modify this, by it seems to me that the adjoint of Vij must …
=> Exchange and Shared memory

src/mrchem/qmoperators/ExchangePotential.cpp, src/mrcpp/constants.h, src/mrcpp/mwoperators/ABGVOperator.h, src/mrcpp/mwoperators/ConvolutionOperator.cpp, src/mrcpp/mwoperators/PHOperator.h, src/mrcpp/mwtrees/FunctionTree.cpp, src/mrcpp/mwtrees/FunctionTree.h, src/mrcpp/mwtrees/OperatorTree.cpp, src/mrcpp/mwtrees/OperatorTree.h, src/mrcpp/mwtrees/SerialFunctionTree.cpp, src/mrcpp/mwtrees/SerialFunctionTree.h, src/mrcpp/mwtrees/SerialOperatorTree.cpp, src/mrcpp/mwtrees/SerialOperatorTree.h, src/mrcpp/mwtrees/SerialTree.h
Not really a significant performance improvement, but much cleaner.
(Simple, but this change was not possible in earlier versions, as we needed control of the position in memory for "stackstatus", which is not the case for vectors (they can be relocated))
=> maxAllocNodes removed! stackStatus now vector

src/mrchem/qmfunctions/Density.cpp, src/mrchem/qmfunctions/DensityProjector.cpp, src/mrchem/qmfunctions/OrbitalAdder.cpp, src/mrchem/qmfunctions/OrbitalVector.cpp, src/mrchem/qmfunctions/OrbitalVector.h, src/mrchem/qmoperators/ExchangePotential.cpp, src/mrchem/qmoperators/FockOperator.cpp, src/mrchem/qmoperators/IdentityOperator.cpp, src/mrchem/scf_solver/EnergyOptimizer.cpp, src/mrchem/scf_solver/GroundStateSolver.cpp, src/mrcpp/mwtrees/SerialFunctionTree.cpp, src/mrcpp/mwtrees/SerialFunctionTree.h, src/mrcpp/mwtrees/SerialOperatorTree.cpp, src/mrcpp/mwtrees/SerialOperatorTree.h, src/mrcpp/mwtrees/SerialTree.h
orbsIx had fixed dimensions. This was wrong. It is now a dynamic vector with no size limitations.
This caused crashes for serial runs if the number of orbitals per mpi was larger that workOrbVecSize.
Bug in MPI orbitalsend, when many orbitals has been corrected.
Delete chunks for gennodes directly after that gennodes are removed. (not sure it helps, since when gennodes are removed we are probably done with the orbital, and if not the chunks could be reused).
=> Bug fix, orbsIx changed, delete genchunks and small adjustements for multi-computenodes runs

src/mrchem/qmfunctions/OrbitalAdder.cpp, src/mrchem/qmfunctions/OrbitalAdder.h, src/mrchem/qmfunctions/OrbitalVector.cpp, src/mrchem/qmoperators/ExchangeOperator.h, src/mrchem/qmoperators/ExchangePotential.cpp, src/mrchem/qmoperators/FockOperator.cpp, src/mrchem/qmoperators/IdentityOperator.cpp, src/mrchem/scf_solver/EnergyOptimizer.cpp, src/mrchem/scf_solver/GroundStateSolver.cpp, src/mrchem/scf_solver/GroundStateSolver.h, src/mrchem/scf_solver/HelmholtzOperatorSet.cpp, src/mrchem/scf_solver/HelmholtzOperatorSet.h, src/mrchem/scf_solver/LinearResponseSolver.cpp, src/mrchem/scf_solver/LinearResponseSolver.h, src/mrchem/scf_solver/OrbitalOptimizer.cpp, src/mrchem/scf_solver/SCF.h, src/mrcpp/MathUtils.cpp, src/mrcpp/constants.h
Different changes to use less memory:
1) Compute only own Helmholt operators. Do not attempt to reuse for parallel runs.
2) Rotate exchange orbitals using smaller buffer (workOrbVec)
3) Clear more frequently
Other:
Set  MachineZero = 1.0e-14L, since for "L-F" in setupHelmholtzArguments it was sometimes, above the threshold only because of machine precision limits.
Set a fixed seed in matrixNorm2, so as to get identical results, independently of the method used (mpi and serial runs could give different results because of this in some cases).
Note: With intel 2015 compiler, for large molecules, the code will use huge amounts (>20GB) of extra memory because of a compiler bug! (the memory used, as defined by top for instance, will increase for each call to allocGenChildren. It can look like a …
=> Memory save

src/mrchem/qmoperators/KineticOperator.cpp
In principle it's still N^2 in the scalar product, but
in practice the time is spent in d/dx phi_i, which is
order N.
=> Reduce scaling of kinetic matrix from N^2 to 2N

cmake/compiler_flags/Intel.C.cmake, cmake/compiler_flags/Intel.CXX.cmake, src/mrchem/qmfunctions/Density.cpp, src/mrchem/qmfunctions/OrbitalVector.cpp, src/mrchem/qmoperators/CoulombOperator.h, src/mrcpp/mwtrees/GenNode.h, src/mrcpp/mwtrees/MWNode.cpp, src/mrcpp/mwtrees/OperatorNode.h, src/mrcpp/mwtrees/ProjectedNode.h
1) OMP memory leak 
2) MPI_Waitall: should fix [issue 56](https://github.com/MRChemSoft/mrchem/issues/56) 
3) Changed compiler optimization flag from O3 to O2. O3 was giving Bus errors sometimes (seldom and randomly) in big calculations. O2 does not seem to go slower.
4) Added a "if(isLeafNode)" in retrieveNode. This is to avoid setting and unsetting locks and queuing when there is nothing to wait for.
5) Increased the size of shared memory to 2000MB. 500MB was not enough for 161 orbitals systems.
( 6. my editor now remove trailing white space automatically )
With these changes, a HF calculation can be performed on ch4_020 (81 orbitals) on 9 compute-nodes or ch4_040 (161 orbitals) on 27 compute-nodes (relprec 1E-6). Localized orbitals must be used for minimizing memory and CPU usage. 1 …
=> parallel improvements

src/mrcpp/mwtrees/GenNode.h, src/mrcpp/mwtrees/OperatorNode.h, src/mrcpp/mwtrees/ProjectedNode.h
The pull request "removed node_lock" did not merge correctly with "parallel improvements".
In the  "removed node_lock", the "node_lock destroy" introduced in "parallel improvements" was removed again, but something went wrong in the merge process.
This pull request removed the "node_lock destroy" again.
=> repaired merge

src/mrcpp/mwtrees/MWNode.cpp, tests/CMakeLists.txt
This pull request adds a missing CBLAS header include and BLAS library link so that MRChem can be built with BLAS.
=> Add missing include and link to compile MRChem with BLAS.

cmake/custom/blas.cmake, config.h.in, src/mrchem/MREnv.cpp, src/mrcpp/MathUtils.cpp, src/mrcpp/mwbuilders/ConvolutionCalculator.cpp, src/mrcpp/mwbuilders/DerivativeCalculator.cpp, src/mrcpp/mwtrees/FunctionNode.cpp, src/mrcpp/mwtrees/MWNode.cpp
As requested in #81, this is a pull request that eliminates CBLAS in favor of BLAS support inside Eigen3.
Note that to actually compile the code against the present version of Eigen3, you need to address a bug in Eigen3 by adding a missing include statement
```
$ hg diff
diff -r 3a08a093adac Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h
--- a/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h     Mon Apr 09 13:29:26 2018 +0200
+++ b/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h     Tue Apr 10 15:51:12 2018 +0300
@@ -33,6 +33,8 @@
#ifndef EIGEN_TRIANGULAR_MATRIX_MATRIX_BLAS_H
#define EIGEN_TRIANGULAR_MATRIX_MATRIX_BLAS_H
+#include "../../misc/blas.h"
+
namespace Eigen {
namespace internal {
```
=> Remove cblas calls, use EIGEN_USE_BLAS instead.

external/CMakeLists.txt, src/CMakeLists.txt, src/SCFDriver.cpp, src/SCFDriver.h, src/mrchem.in, src/qmfunctions/qmfunctions.h, src/qmoperators/two_electron/CMakeLists.txt, src/qmoperators/two_electron/FockOperator.cpp, src/qmoperators/two_electron/XCFunctional.cpp, src/qmoperators/two_electron/XCFunctional.h, src/qmoperators/two_electron/XCOperator.h, src/qmoperators/two_electron/XCPotential.cpp, src/qmoperators/two_electron/XCPotential.h
PR for the NEW xcfun in the NEW mrchem. 
Now we can use xcfun both with closed and open-shell (as before) and we can also choose whether to use explicit derivatives (wrt to density and gradient) or gamma-type ones (wrt to density and gamma). The former seems to be more stable (less affected by numerical instabilities in some functionals, such as f.ex. BLYP), and it should be easier to extend to higher order derivatives (hessian and further...)
The code has been tested on both closed and open shell cases..
=> Xcfun update2

src/SCFDriver.cpp, src/SCFDriver.h, src/chemistry/CMakeLists.txt, src/chemistry/Molecule.cpp, src/chemistry/Molecule.h, src/chemistry/chem_utils.cpp, src/chemistry/chem_utils.h, src/mrchem.in, src/properties/SCFEnergy.h, src/qmoperators/RankZeroTensorOperator.h, src/qmoperators/one_electron/ElectricFieldOperator.h, src/qmoperators/one_electron/H_E_dip.h, src/qmoperators/one_electron/MagneticFieldOperator.h, src/qmoperators/one_electron/NuclearOperator.cpp, src/qmoperators/one_electron/NuclearOperator.h, src/qmoperators/two_electron/FockOperator.cpp, src/qmoperators/two_electron/FockOperator.h, tests/CMakeLists.txt, tests/qmoperators/CMakeLists.txt, tests/qmoperators/electric_field_operator.cpp
The external potential is reintroduced as a simple additional operator in the Fock Operator.
=> Reimplementing external field

src/SCFDriver.cpp, src/qmoperators/RankZeroTensorOperator.cpp, src/qmoperators/two_electron/FockOperator.cpp, src/qmoperators/two_electron/FockOperator.h, src/scf_solver/CMakeLists.txt, src/scf_solver/HelmholtzVector.cpp, src/scf_solver/LinearResponseSolver.cpp, src/scf_solver/LinearResponseSolver.h, src/scf_solver/OrbitalOptimizer.cpp
Imported preliminary LinearResponseSolver from the old code. Only works for imaginary perturbations in pure DFT where the electronic Hessian contribution vanishes, e.i. static magnetic perturbations. Tested for LDA magnetizabilities. The structure is likely to change in the future, but it is a starting point for implementing and testing the Hessians.
=> Response solver

src/SCFDriver.cpp, src/qmfunctions/density_utils.cpp, src/qmoperators/two_electron/CoulombPotential.cpp, src/qmoperators/two_electron/CoulombPotential.h, src/qmoperators/two_electron/FockOperator.cpp, src/qmoperators/two_electron/FockOperator.h, src/scf_solver/EnergyOptimizer.cpp
The helium example crashed in the second SCF procedure (energy optimization) due to a faulty initialization of the n+1 FockOperator. Also fixed a memleak in CoulombPotential.
=> Energy optimizer

.circleci/config.yml, .gitignore, cmake/custom/testing_macros.cmake, tests/h2/CMakeLists.txt, tests/h2/test, tests/h2o/CMakeLists.txt, tests/h2o/test, tests/li/CMakeLists.txt, tests/li/test, tests/runtest/cli.py, tests/runtest/run.py, tests/runtest/version.py, tests/unit_tests.cpp
Unit tests
------------
- Added `MPI_Init` and `MPI_Finalize` so that the tests run without failing, but all test cases are fully sequential
Integration tests
--------------------
- Update `runtest` to allow for `mpirun` launch agent
- The test cases are run with a fixed number of MPI processes when compiled with MPI options
- Relaxed the success criterion for the properties, since we currently cannot expect identical results when running with different number of MPI procs
Not at all sure if this is a sensible way of passing arguments from CMake -> CTest -> runtest
=> Activate MPI test case on CircleCI

src/initial_guess/core.cpp, src/initial_guess/sad.cpp, src/parallel.cpp, src/qmfunctions/Density.cpp, src/qmfunctions/Density.h, src/qmfunctions/Orbital.cpp, src/qmfunctions/Orbital.h, src/qmfunctions/QMFunction.cpp, src/qmfunctions/QMFunction.h, src/qmfunctions/density_utils.cpp, src/qmfunctions/density_utils.h, src/qmfunctions/orbital_utils.cpp, src/qmfunctions/orbital_utils.h, src/qmfunctions/qmfunction_fwd.h, src/qmfunctions/qmfunction_utils.cpp, src/qmfunctions/qmfunction_utils.h, src/qmoperators/RankZeroTensorOperator.cpp, src/qmoperators/one_electron/QMPotential.cpp, src/qmoperators/two_electron/CoulombPotential.cpp, src/qmoperators/two_electron/ExchangePotential.cpp, src/scf_solver/Accelerator.cpp, src/scf_solver/EnergyOptimizer.cpp, src/scf_solver/GroundStateSolver.cpp, src/scf_solver/KAIN.cpp, src/scf_solver/LinearResponseSolver.cpp, tests/qmfunctions/density.cpp, tests/qmfunctions/orbital.cpp, tests/qmfunctions/orbital_vector.cpp
I restructured the `QMFunction` to make the `Orbital` and `Density` functionality simpler and more consistent. This will also help in the generalization of shared memory that should be done in #135. It's probably a bit too much for a proper review, but @ilfreddy please have a look at the changes it lead to in the `density::compute()` routines.
=> Dens class

src/mrchem.in
The whole `DFT` section of the input can now be omitted for the most standard functionals. Currently implemented for LDA, BLYP, B3LYP, PBE, PBE0, BP86 and PW91.
Old setup:
```
WaveFunction {
method = DFT
}
DFT {
exact_exchange = 0.2
$functionals
BECKEX 0.80
LYPC   1.00
$end
}
```
New setup:
```
WaveFunction {
method = B3LYP
}
```
=> Simplified input for standard DFT functionals

src/qmfunctions/orbital_utils.cpp
Bug in localization setup: the rotation of the orbitals was done twice, once in calc_localization_matrix and once in localize.
The effect is simply that the orbitals are not localized (and not canonical either). The scf may still converge to a correct value. 
Until 10th December the localization was still working.
=> bug in localization: orbital rotation was done twice

.circleci/config.yml
When setting the Docker image to `mrchemsoft/circleci_ubuntu-18.04` we default to using `latest`. That is, however, a moving target and can make it hard to reproduce build failures locally. With a tagged Docker image we now exactly which version was used.
=> Use specific Docker image tag, rather than latest

src/utils/RRMaximizer.cpp
Small gain in cpu time, but only a few lines extra.
Also set std=c++14 compiler flag (for compatibility with mrcpp)
=> omp parallelization of Hessian matrix mult for localization

src/parallel.cpp, src/qmfunctions/density_utils.cpp
It seems there's a problem if we call `mpi::send_function()` with a shared density, e.i. the grand master sends a density from its shared memory to the sub masters who receives into their shared memory.
Old compute density algorithm
--------------------------------------
1) All ranks compute a non-shared local density from own orbitals
2) All local densities are sent to the grand master who adds the contributions in place into its non-shared local density
3) Grand master copies the result into shared memory
4) Grand master distributes the shared density to the sub masters who shares it with their sibling ranks
New compute density algorithm
--------------------------------------
1) All ranks compute a non-shared local density from own orbitals
2) All local densities are sent to the grand …
=> Fix performance issues with shared density

src/qmfunctions/density_utils.cpp
The part densities where broadcasted among shared-slaves with same ranks. Only sharemasters should broadcast densities. (could, in some cases, give accounting errors when the trees were deleted, though did not give wrong results. (Also with the latest getNchunksUsed this can not happen))
=> broadcast_density only among share_masters, not among slaves

external/upstream/fetch_getkw.cmake, external/upstream/fetch_mrcpp.cmake, external/upstream/fetch_xcfun.cmake
* Remove `GIT_SHALLOW 1` in MRCPP, XCFun and Getkw so that we can point to older revisions.
* Update MRCPP and Getkw to latest and greatest.
=> Fix FetchContent

cmake/custom/main.cmake, external/upstream/fetch_getkw.cmake, src/mrchem.in
My take on #207 in tandem with dev-cafe/libgetkw#32. I have tested with a prebuilt and a fetched getkw. When dev-cafe/libgetkw#32 is in, I'll switch back to the right commit on the canonical repo.
=> Fix path to getkw Python packages

doc/mrchem_manual.rst, src/SCFDriver.cpp, src/initial_guess/core_guess.cpp, src/initial_guess/gto_guess.cpp, src/initial_guess/lsdalton/lsdalton.py, src/initial_guess/sad_guess.cpp, src/mrchem.cpp, src/mrchem.h, src/mrchem.in, src/mrenv.cpp
The input file is read in and converted to lowercase before moving on to the parser.
This fixes the case at the very beginning, allowing users to not care about the case of input parameters.
When used internally, all keys are accessible in _lowercase_
=> Implement case-insensitive input reading

src/CMakeLists.txt
The removed line just looks like an incomplete duplicate of what going on, on lines: 87 to 91 in `src/CMakeLists.txt`. At the very least it seems to run fine without it.
=> Remove redundant lines

src/initial_guess/core.cpp, src/initial_guess/core.h, src/initial_guess/sad.cpp
Fixing issue #244. Problem was not open-shell but rather that the core guess orbitals were not correctly distributed with MPI. Moved the `initial_guess::rotate_orbitals` from sad.cpp to core.cpp since the latter is more fundamental.
=> Bug fix #244: Core initial guess

src/input/mrchem.in, tests/h2_pol_lda/mrchem.inp, tests/h2_pol_lda/test, tests/runtest_config.py
`mrchem.in` accepts input files both in `getkw` format and `json` format.
to use `json` as input add the `--json` or `-j` flag e.g.;
`./mrchem --json mrchem.json`
`./mrchem -j mrchem.json`
the parsed `json` are now named `mrchem_parsed.json`
The following files are both accepted by `mrchem.in` and produces the same
`mrchem_parsed.json` files 
Getkw format:
```
world_prec = 1.0e-6
world_size = 6
Molecule {
translate = true
$coords
O   0.0000     0.0000     0.0000
H   0.0000     1.4375     1.1500
H   0.0000    -1.4375     1.1500
$end
}
WaveFunction {
method = HF
}
Properties {
scf_energy = true
}
SCF {
kain = 3
initial_guess = sad_sz
}
```
Json format:
```
{
"world_prec": 1e-06,
"world_size": 6,
"Molecule": {
"translate": true,
"coords": "O   0.0000     0.0000     0.0000\n
H   0.0000 …
```
=> Accept json format in input files

.gitignore, src/chemistry/Molecule.cpp, src/driver.cpp, src/properties/DipoleMoment.h, src/properties/Magnetizability.h, src/properties/NMRShielding.h, src/properties/Polarizability.h, src/properties/QuadrupoleMoment.h, src/utils/math_utils.cpp, src/utils/math_utils.h, src/utils/print_utils.cpp, tests/h2_pol_lda/reference/mrchem.stdout, tests/h2_pol_lda/test, tests/li_pol_lda/reference/mrchem.stdout, tests/li_pol_lda/test
Initialize properties to NaN, so that un-computed properties are not confused with zero value.
E.g. polarizability computed only in x and y `directions=[1,1,0]` will look like this
```
======================================================================
Polarizability
----------------------------------------------------------------------
Wavelength            :           (nm)                    694.573171
Frequency             :           (au)                      0.065600
:         (cm-1)                  14397.331226
----------------------------------------------------------------------
Total tensor          :       1.668198       0.000000       0.000000
:       0.000000       1.668198       0.000000
:            N/A            N/A            N/A
Isotropic average     :           (au) …
```
=> Property printing

src/qmoperators/two_electron/ExchangePotentialD1.cpp, src/scf_solver/GroundStateSolver.cpp, src/scf_solver/LinearResponseSolver.cpp
Response solver printed out `current_prec` and `start_prec` instead of `start_prec` and `final_prec`
=> Fix displayed final precision in response

.travis.yml, src/driver.cpp, src/initial_guess/core.cpp, src/initial_guess/gto.cpp, src/initial_guess/mw.cpp, src/initial_guess/mw.h, src/initial_guess/sad.cpp, src/input/mrchem.in, src/input/template.yml, src/qmfunctions/ComplexFunction.h, src/qmfunctions/Orbital.cpp, src/qmfunctions/QMFunction.cpp, src/qmfunctions/QMFunction.h, src/qmfunctions/orbital_utils.cpp, src/qmfunctions/orbital_utils.h
Improve MW guess to allow re-projection of MW orbitals onto a different MRA (world and basis).
Typical work flow I
------------------------
1. Run low prec calculation and write orbitals
```
world_prec = 1.0e-3    # results in order 5
SCF {
guess_type = sad_dz
write_orbitals = true
}
```
2. Rerun calculation with higher prec with MW guess
```
world_prec = 1.0e-6    # results in order 9
SCF {
guess_type = mw
}
```
By default paired/alpha/beta orbitals are written to (and read from) `orbitals/phi_[p/a/b]` but you can override in the `Files` input section
```
Files {
file_mw_paired = orbitals/phi_p  # where 'mw' guess reads paired orbitals
file_mw_alpha = orbitals/phi_a   # where 'mw' guess reads alpha orbitals
file_mw_beta = orbitals/phi_b    # where 'mw' guess reads beta orbitals …
```
=> Revamp MW guess

src/driver.cpp, src/initial_guess/CMakeLists.txt, src/initial_guess/chk.cpp, src/initial_guess/chk.h, src/initial_guess/mw.cpp, src/input/mrchem.in, src/input/template.yml, src/qmfunctions/orbital_utils.cpp, src/scf_solver/GroundStateSolver.cpp, src/scf_solver/GroundStateSolver.h, src/scf_solver/LinearResponseSolver.cpp, src/scf_solver/LinearResponseSolver.h, src/scf_solver/SCFSolver.h
Added new checkpointing feature which dumps orbitals at each iteration, so that a particular run can be restarted if something happens (out of memory, time limit, non-convergence, etc). This feature is slightly different from the new MW initial guess in #276, but more closely resemble the old MW guess. Some notable differences:
MW write
------------
- only final orbitals
- keywords: `SCF { write_orbitals = true }` and ` SCF { path_orbitals = "orbitals" }`
- separates between paired/alpha/beta orbitals in the file names, by `phi_p`/`phi_a`/`phi_b` extension
MW read
------------
- keywords: `SCF { guess_type = mw }` and `Files { guess_phi_<p/a/b> = orbitals/phi_<p/a/b> }`
- re-projects MW orbitals, which allows for different MRAs
- sets up orbital configuration (N orbs, spins, etc) from new …
=> Guess cleanup part 2: Checkpointing

src/CMakeLists.txt
Small fix from @robertodr to make MAC compiler postopne resolving undefined symbols.
=> CMakeList fix for MAC

external/upstream/fetch_xcfun.cmake, src/CMakeLists.txt
This fixes an obscure issue with dynamic linking that has annoyed @stigrj for quite a long time now. I still don't understand the original issue, but we agreed it's fine to have this fix in rather than break our teeth on getting dynamic linking right.
=> Build libmrchem as static library

cmake/custom/sad_basis.cmake
`SAD_BASIS_DIR` was not defined, so the files were not installed.
Now the installed package is finally fully self-contained, and we can nuke the source repo after installation :tada:
=> Fix installation of SAD input files

.github/workflows/build-test.yml
So we test on macOS... This builds in release mode with OpenMP enabled and no architecture-specific flags. It gets Eigen, JSON library, XCFun, and MRCPP from conda-forge.
=> Add build and test action

python/mrchem/helpers.py, src/driver.cpp
Fixes issue reported by Anders that `chk` initial guesses was limited by the chosen `guess_prec`, due to an orbital rotation immediately after loading the orbitals. Now the `chk` guess will get the full `world_prec` for this rotation. All other guesses will still use `guess_prec`, but they are anyway inherently limited by this precision in their construction (unlike `chk`).
=> Fix precision issue with chk initial guess

.github/workflows/all-hail-minazo-bot.yml, src/driver.h
See here: https://github.com/danger/danger/issues/1103#issuecomment-635539947
Minazo is partially healed: 
1. If there are no comments to post, the job completes successfully.
2. If there are comments to post, the job fails because the bot's permissions are not sufficient to comment on open PRs.
I have changed the event that triggers Minazo from `pull_request` to `pull_request_target`, which presumably exposes secrets correctly. However, changing triggers is not picked up until the PR is merged...
=> Change fetch-depth

.github/workflows/all-hail-minazo-bot.yml, src/qmfunctions/ComplexFunction.h
Fixes MPI deadlock introduced in #328. The lock is triggered whenever the MPI orbital bank occupies _all but one_ rank on a particular node, _and_ at the same time a function is allocated in shared memory. Then the remaining rank on the node would mark the function as non-shared (because it's not actually sharing with anyone), which lead to subsequent `broadcast_function` to be called with a different communicator, thus deadlock.
=> Fix MPI deadlock

src/parallel.cpp
Threading lead to highly unpredictable results for large matrix-matrix multiplications, which caused Core and SAD guesses to fail for larger systems.
=> Limit Eigen to single thread

.github/mrchem-codecov.yml, .github/mrchem-gha.yml, doc/conf.py, doc/requirements.txt, doc/users/betzy_example.job, doc/users/running.rst, external/upstream/fetch_mrcpp.cmake, src/parallel.cpp, src/parallel.h, src/qmfunctions/orbital_utils.cpp, src/qmfunctions/orbital_utils.h, src/qmoperators/two_electron/ExchangePotentialD1.cpp, src/utils/NonlinearMaximizer.cpp, src/utils/RRMaximizer.cpp
New faster method for rotation and dot product of orbital vectors. Those are the parts that scale as 0(N²)
The idea is to rotate one nodes at a time; this can be done as a matrix multiplication which is extremely fast.
For Valinomycine (300 orbitals), rotation is up to 50 times faster. Overall 5 times faster LDA calculation.
The benefit is largest for large molecules.
Could still relatively easily be further optimized, as the mpi version does not even use omp (!) for example. However other parts are now the bottleneck (XC and Exchange) and should be optimized first.
The functions that have been replaced are "rotate" and "overlap". Unfortunately those have become "monolithic" and heavy, since they are written for efficiency (avoid data copying and use pointer and indices manipulation). …
=> Superfast rotate

doc/users/Betzy_example.job, doc/users/running.rst, src/driver.cpp, src/parallel.cpp, src/parallel.h, src/qmfunctions/OrbitalIterator.cpp, src/qmfunctions/OrbitalIterator.h, src/qmfunctions/orbital_utils.cpp, src/qmfunctions/orbital_utils.h, src/qmoperators/two_electron/ExchangePotential.cpp, src/qmoperators/two_electron/ExchangePotential.h, src/qmoperators/two_electron/ExchangePotentialD1.cpp, src/qmoperators/two_electron/ExchangePotentialD1.h, src/qmoperators/two_electron/ExchangePotentialD2.cpp, src/qmoperators/two_electron/ExchangePotentialD2.h, src/scf_solver/GroundStateSolver.cpp, src/scf_solver/SCFSolver.cpp, src/utils/Bank.cpp, src/utils/Bank.h, src/utils/CMakeLists.txt
Refactoring of Bank. Main changes:
- Moved all Bank related to own files utils/Bank.cpp
- The usage of the Bank is now through the `BankAccount` class. Once a type `BankAccount` is defined, it can be used similarly to an array (or rather a std::map) to put and get orbitals or data. 
- The `BankAccount` are private, so no interference between different parts of the code. 
- One can open several `BankAccounts` (for Bra and Ket orbitals for example). 
- They are cleaned up automatically (destructor) when getting out of scope.
- Note that `BankAccount` class declaration (creator) is collective, i.e. it must be declared by all MPI at once.  
- Slightly faster
=> Bank upgrade

src/driver.cpp, src/environment/SCRF.cpp, src/environment/SCRF.h, src/qmoperators/two_electron/ReactionOperator.h, src/qmoperators/two_electron/ReactionPotential.cpp, src/qmoperators/two_electron/ReactionPotential.h, tests/solventeffect/reaction_operator.cpp
- The SCRF instance was not copied correctly, so I made it a `unique_ptr` and `move` it into the `ReactionPotential`.
- The `d_cavity` vector was not properly deallocated
- The `mo_residual` variable was not initialized in the constructor
- Removed some "noisy" documentation
Not sure if any of this helps with the issues we have seen, I think they might be unrelated to the solvent code.
=> Solvent fixes

src/mrdft/MRDFT.cpp, src/mrdft/xc_utils.cpp
Another simple bugfix, closes #374
=> Fix wrong size parameter in contracted XC output

src/qmfunctions/orbital_utils.cpp
Only triggered when size of `mpi::comm_orb` is greater than number of orbitals, i.e. when some MPI ranks does not have any orbitals. Closes #378.
=> Fix uninitialized value in orbital::rotate

src/analyticfunctions/NuclearGradientFunction.h, src/driver.cpp, src/qmoperators/one_electron/H_BM_dia.h, src/qmoperators/one_electron/H_MB_dia.h, src/qmoperators/one_electron/NuclearGradientOperator.h
The smoothing parameter for the `r/r^3` function, as computed for use in nuclear gradients, was not sufficiently tight for NMR calculations. The old parameter was computed as described by [Yanai et.al.](https://aip.scitation.org/doi/10.1063/1.1768161) as
```
c = [prec / (0.00435*Z^5*N_atoms)]^(1/3)
= [prec / 0.00435]^(1/3), with Z = N_atoms = 1 in the NMR operator
```
The new parameter is simply set to
```
c = prec, in the NMR operator
```
This is the same as in v1.0.1, and seems to give nice and consistent NMR parameters, but we should reconsider the forms and parameters of all our smoothed functions (nuclear potential, nuclear gradient, NMR operator, ZORA potential, etc). A quick peek into the MADNESS source reveals that they are no longer using the same form for their potentials.
=> Fix NMR shieldings, closes #384

src/driver.cpp, src/qmoperators/one_electron/NuclearOperator.cpp
Scale the relative prec for Nuclear potential with box size. 
V.norm increase with 6th root of box volume = additional scaling factor.
Note that the prec for the " allreducePotential" should be rethinked too. It seems to use absolute prec, not relative prec, but probably it is so small, that there is no neglect of nodes anyway, which is probably what we want.
The correct treatment would be to not copy the entire nuclear potential everywhere, but to treat it "locally", i.e. save the nodes in bank, and when multiplied by an orbitalvector, loop over orbitals for fixed node, (instead of loop over nodes for fixed orbitals). This can easily(?) be done transparently.
=> Nuclear potential prec scaled with box size

python/mrchem/api.py
The motivation for this PR is to help prevent people (me) from submitting jobs to an HPC cluster only to find it failing due to an invalid multiplicity after waiting several hours for it to start 😭 
This is a suggestion for a quick sanity check of the specified multiplicity during the input parsing, instead of performing the check only in `driver.cpp`. Now an invalid multiplicity can be caught during a dry run (no need to call the executable with invalid input). The original check in `driver.cpp` is untouched, as in principle someone could edit the `program.json` file directly and pass this to `mrchem.x`. 
The following checks have been added to `./python/mrchem/api.py`:
- Too high multiplicities that would require `n_unpaired > n_electrons` (which was not currently checked for)
- …
=> Sanity checking the multiplicity during input parsing

recipes/Singularity.openmpi4.0
This fixes the failing GHA build, as the old version download suddenly resulted in a 404
=> Update Slurm version in Singularity recipe

python/mrchem/input_parser/plumbing/atoms.py, python/mrchem/input_parser/plumbing/getkw.py
If an older `pyparsing` is available (and it usually always is), then it is imported, but it won't work with the parser generated by `parselglossy`. I've added a check so that if the existing `pyparsing` is not of major version >=3, the local copy is used instead. I will port this to `parselglossy` itself as well.
=> Fix importing of pyparsing

doc/users/betzy_example.job, doc/users/running.rst
As @gitpeterwind has mentioned we could run in Betzy in a more general way, which is what i tried to show here in the docs.
=> Add alternative way of running MRChem in Betzy to docs

src/environment/SCRF.cpp, tests/li_solv/li.inp, tests/solventeffect/reaction_operator.cpp
Turned out to be a comically simple fix. By initializing the MO residual to `1.0` instead of `-1.0` we trigger the dynamic threshold also for the 0th iteration. For cases when we want to compute the total energy accurately on the initial guess, use `dynamic_thrs = false`.
@Gabrielgerez please try this version on some real-world cases.
Closes #426
=> Use dynamic thrs in initial SCRF

src/initial_guess/gto.cpp
@gitpeterwind , not exactly sure why the rank should be set incrementally by the number of orbitals rather than the number of MPI ranks, but this is the way it's done in the `core::project_ao` equivalent, and it seems to work :shrug:
=> Fix mpi error on SAD_GTO guess, closes #452

python/mrchem/validators.py
Simply removed the attempted `:math:` rendering in the docstring which caused the error in #457
=> Remove :math: rendering in validator docstring, fixes #457

.readthedocs.yml, doc/requirements.txt
the key `build.os` will start being a requirement soon (see [link](https://blog.readthedocs.com/use-build-os-config/) )
Hopefully this fixes any issues
=> Fix incoming build error in rtd

README.md
Removed user support link to the old slack channel. We can probably replace it with something else, but I think it is better to stop users from hoping too much
=> Remove dead link to old slack channel

src/tensor/RankZeroOperator.cpp
The RankZeroOperator could only be applied to "my" orbitals. Now always applied if non empty orbital. 
Thank you Moritz for a detailed bug report!
=> operator bugfix
