src/mrcpp/CMakeLists.txt, src/mrcpp/GreensKernel.cpp, src/mrcpp/GreensKernel.h, src/mrcpp/HelmholtzKernel.cpp, src/mrcpp/HelmholtzKernel.h, src/mrcpp/PoissonKernel.cpp, src/mrcpp/PoissonKernel.h, tests/mrcpp/CMakeLists.txt, tests/mrcpp/helmholtz_kernel.cpp, tests/mrcpp/poisson_kernel.cpp
Added Poisson and Helmoltz kernels and their relative tests
=> Greenskernel

NEWS, TODO
these empty files are otherwise almost guaranteed to become outdated
=> rm NEWS and TODO

docs/mrcpp_api.rst
The old MRCPP documentation was outdated
=> update mrcpp api with new notation

src/mrchem/qmfunctions/DensityProjector.cpp, src/mrchem/qmfunctions/OrbitalVector.cpp, src/mrchem/qmfunctions/OrbitalVector.h, src/mrcpp/mwtrees/SerialTree.h, src/mrcpp/parallel.h
Small changes to make the code compile _without_ MPI, as well as run _with_ MPI
=> Compile issues

src/mrchem/qmoperators/FockOperator.cpp, src/mrchem/qmoperators/QMOperatorExp.cpp
Bug when not all MPI processes have same number of orbitals (line 135 in FockOperator.cpp).
Style changes.
Parallelized trace (issue #31).
=> small MPI bug and parallel trace

src/mrchem/scf_solver/Accelerator.cpp, src/mrchem/scf_solver/KAIN.cpp, src/mrcpp/mwtrees/FunctionTree.cpp, src/mrcpp/mwtrees/FunctionTree.h, src/mrcpp/mwtrees/MWNode.cpp, src/mrcpp/mwtrees/MWNode.h, src/mrcpp/mwtrees/SerialFunctionTree.cpp
The updates where incorrectly sent to the other processes (to few elements sent in mpi_reduce)
=> bug in KAIN parallelization corrected

src/SCFDriver.cpp, src/SCFDriver.h, src/analyticfunctions/NuclearGradientFunction.cpp, src/chemistry/Molecule.cpp, src/chemistry/Molecule.h, src/mrchem.in, src/properties/GeometryDerivatives.h, src/properties/properties.h, src/qmoperators/one_electron/X_rm3.h
Squashed the geometric derivative part of Peters PR #116
=> Geometric derivative

src/qmfunctions/orbital_utils.cpp, src/utils/NonlinearMaximizer.cpp, src/utils/NonlinearMaximizer.h, src/utils/RRMaximizer.cpp, src/utils/RRMaximizer.h
=> Localization without storing Hessian

.circleci/config.yml, src/SCFDriver.cpp, src/initial_guess/sad.cpp, src/mrenv.cpp, src/parallel.cpp, src/qmfunctions/OrbitalIterator.cpp, src/qmfunctions/OrbitalIterator.h, src/qmfunctions/orbital_utils.cpp, src/qmoperators/two_electron/ExchangeOperator.h, src/qmoperators/two_electron/ExchangePotential.cpp, src/qmoperators/two_electron/ExchangePotential.h, src/scf_solver/EnergyOptimizer.cpp
Squashed the MPI part of Peter's PR #116.
Fixed the merge conflicts and the bug we discovered at the group meeting, and the code now runs successfully in parallel.
=> Improved MPI functionalities

.clang-format, .gitattributes, .githooks/LICENSE-C++, .githooks/LICENSE-Python, .githooks/canonicalize_filename.sh, .githooks/license_maintainer.py, .githooks/pre-commit, .githooks/pre-commit-clang-format, .githooks/pre-commit-license-maintainer, README.md, src/scf_solver/Accelerator.cpp, src/scf_solver/Accelerator.h, src/scf_solver/EnergyOptimizer.cpp, src/scf_solver/EnergyOptimizer.h, src/scf_solver/GroundStateSolver.cpp, src/scf_solver/GroundStateSolver.h, src/scf_solver/HelmholtzVector.cpp, src/scf_solver/HelmholtzVector.h, src/scf_solver/KAIN.cpp, src/scf_solver/KAIN.h, src/scf_solver/LinearResponseSolver.cpp, src/scf_solver/LinearResponseSolver.h, src/scf_solver/OrbitalOptimizer.cpp, src/scf_solver/OrbitalOptimizer.h, src/scf_solver/SCF.cpp, src/scf_solver/SCF.h
To add the license header on top of the source files:
```
./.githooks/pre-commit-license-maintainer
```
I am not doing since it would touch all files and I think it's better @stigrj does something like that.
=> Formatting, licensing, ang Git hooks

src/analyticfunctions/HarmonicOscillatorFunction.h, src/analyticfunctions/HydrogenFunction.h, src/analyticfunctions/NuclearFunction.h, src/analyticfunctions/NuclearGradientFunction.h, src/chemistry/Molecule.cpp, src/utils/gto_utils/Intgrl.cpp, src/utils/gto_utils/Intgrl.h, src/utils/math_utils.cpp
This should fix the permission issue reported in #142.
=> Read-only access to file input 

src/properties/Polarizability.h
Fixes a compiler warning about data member reordering.
=> Reorder initialization list

src/SCFDriver.cpp, src/mrdft/XCFunctional.cpp, src/mrdft/XCFunctional.h, src/qmoperators/two_electron/XCPotentialD2.cpp, src/qmoperators/two_electron/XCPotentialD2.h, tests/h2_pol_lda/CMakeLists.txt, tests/h2_scf_hf/CMakeLists.txt, tests/h2o_energy_blyp/CMakeLists.txt, tests/h_el_field/CMakeLists.txt, tests/li_pol_lda/CMakeLists.txt, tests/li_scf_pbe0/CMakeLists.txt, tests/qmoperators/CMakeLists.txt, tests/qmoperators/xc_hessian.cpp, tests/qmoperators/xc_hessian_pbe.cpp, tests/qmoperators/xc_operator_blyp.cpp
=> GGA hessian implementation

.travis.yml, src/SCFDriver.cpp, src/mrdft/XCFunctional.cpp, src/mrdft/XCFunctional.h, src/mrenv.cpp, src/qmoperators/one_electron/DeltaOperator.cpp, src/qmoperators/one_electron/SpinOperator.cpp, src/utils/gto_utils/AOContraction.cpp, src/utils/gto_utils/OrbitalExp.cpp, tests/unit_tests.cpp
- Update MRCPP and XCFun to Clang friendly versions
- Adapt to minor changes in MRCPP interface
- Add Clang build on Travis
Status
--------
=> Clang compiler

AUTHORS
- Added Roberto and Gabriel to AUTHORS
- Removed e-mail address of former developers
=> Update list of AUTHORS

Pipfile, Pipfile.lock
=> Update Pipfile with pyyaml-4.2b1

doc/index.rst, doc/installation.rst, doc/programmers/maintenance.rst
Expand documentation on the role of Python in MRChem.
Addresses #194
=> Document Pipenv usage

tools/legendre_to_interpolating_basis/convert_script.py, tools/legendre_to_interpolating_basis/legendre_to_interpolating.py
This PR includes the python script used to convert Legendre Basis operators to Legendre Interpolating Operators used in my current mrcpp PL.
=> Add script that converts Legendre Operators to Interpolating Operators

src/mrchem.in
since all input is lowercased before parsing
=> Bugfix: energy unit in lower case

src/scf_solver/HelmholtzVector.cpp
=> bugfix, wait for bank

.travis.yml, cmake/custom/main.cmake, external/upstream/fetch_mrcpp.cmake, external/upstream/fetch_xcfun.cmake
External libraries are compiled (where appropriate) with release flags. I have also updated XCFun to its latest version.
=> Release for externals

src/initial_guess/core.cpp
The `CORE` and `SAD` initial guess did not give MPI invariant results with
```
MPI {
numerically_exact = true
}
```
Now they do
=> Bugfix: MPI numerically exact CORE and SAD guess

src/driver.cpp, src/initial_guess/chk.cpp, src/input/mrchem.in, src/input/template.yml, src/scf_solver/LinearResponseSolver.cpp, src/utils/MolPlotter.h, tests/h2_pol_lda/mrchem.inp, tests/li_pol_lda/mrchem.inp
Implements `mw` and `chk` initial guesses for response calculations. Based on #277.
=> Guess cleanup part 3: Response

src/driver.cpp, src/driver.h, src/input/mrchem.in, src/mrchem.cpp
Final cleanup in `mrchem.in` and `driver.cpp` after all the guess work lately. Only refactoring, no changed features :crossed_fingers: Based on #287
=> Guess cleanup part 4: Final touches

external/upstream/fetch_xcfun.cmake
This version fixes VWN3 for the spin-polarized case
=> Use latest XCFun

.circleci/config.yml, cmake/custom/testing_macros.cmake, src/input/mrchem.in, src/mrenv.cpp, src/mrenv.h, tests/h2_pol_lda/CMakeLists.txt, tests/h2_pol_lda/test, tests/h2_scf_hf/CMakeLists.txt, tests/h2_scf_hf/test, tests/h2o_energy_blyp/CMakeLists.txt, tests/h2o_energy_blyp/test, tests/h_el_field/CMakeLists.txt, tests/h_el_field/test, tests/li_pol_lda/CMakeLists.txt, tests/li_pol_lda/test, tests/li_scf_pbe0/CMakeLists.txt, tests/li_scf_pbe0/test, tests/tester.py
Irons out some wrinkles left when removing the dependency on ``runtest``, most notably some confusion on what the working directory was supposed to be.
=> Clean up after removal of runtest

cmake/custom/main.cmake
Title says it all, had some issues with updating the original PR.
=> Require python 3.6 to run setup

python/CMakeLists.txt, python/mrchem.in
See conda-forge/staged-recipes#12679, which currently builds from this branch on my fork.
=> Changes to create a Conda package

src/qmoperators/QMOperator.h, src/qmoperators/one_electron/IdentityOperator.h, src/qmoperators/one_electron/MomentumOperator.h, src/qmoperators/one_electron/NablaOperator.h, src/qmoperators/one_electron/NuclearOperator.h, src/qmoperators/one_electron/QMPotential.h, src/qmoperators/one_electron/SpinOperator.h
=> Makes QMPotenital non-virtual again!

src/parallel.cpp
Triggered MPI runtime error only when launched through Singularity container
=> Use MPI_INT data type (MPI_INTEGER is Fortran)

.github/Gemfile, .github/Gemfile.lock, .github/workflows/all-hail-minazo-bot.yml, src/initial_guess/sad.cpp, src/utils/gto_utils/Intgrl.cpp, src/utils/gto_utils/Intgrl.h, src/utils/print_utils.cpp, src/utils/print_utils.h
This somehow only manifests in the Conda package... Go figure! :man_shrugging:
=> Fix runtime failure while reading basis set for SAD guess

.github/mrchem-minazo.yml, .github/workflows/all-hail-minazo-bot.yml
=> Clean up actions

src/environment/SCRF.cpp
simple simplification of functions.
=> Simplify getEnergy functions in SCRF.cpp

src/CMakeLists.txt
=> Create OBJECT library from MRChem sources

doc/users/schema_input.json, doc/users/schema_output.json, python/mrchem.in, python/mrchem/helpers.py
I have updated the schemas to include parameters for solvation, ZORA, and sad_gto.
Is there anything else that should be updated there? The constants from #404 will need to be merged after.
=> Bring the schemas à jour

external/catch/catch.hpp
Fixes compilation issue on recent GCC
=> Update Catch to 2.13.5

python/mrchem/input_parser/plumbing/atoms.py, python/mrchem/input_parser/plumbing/getkw.py, src/parallel.cpp, src/qmfunctions/orbital_utils.cpp, src/scf_solver/Accelerator.cpp, src/utils/Bank.cpp
MPI_CXX_DOUBLE_COMPLEX is not supported on some machines
3 "asserts" were stopping the code unnecessarily (only in debug mode).
Typo in history rotation (not used by default)
=> 3 small bug fixes

doc/users/manual.rst, doc/users/qcengine.rst
=> Add documetation on use with QCEngine

doc/users/qcengine.rst
Show how to set up a parallel calculation. I needed to make some more changes to QCEngine to get the correct print out of the parallel set up.
=> One more update to QCEngine documentation

.readthedocs.yml
Hopefully fixes rtd-builds for mrchem
=> add readthedocs.yml, same as for MRCPP

python/mrchem/validators.py
=> Only validate cavity when doing PCM

.github/workflows/build-test.yml, src/mrdft/MRDFT.cpp
DFT energy was not summed cleanly in the omp loop.
=> bug fix dft energy printouts

.github/workflows/build-test.yml
=> Remove macos-12 test (temporarily)
